name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Verify AWS CLI Installation
        run: aws --version

      - name: Checkout code
        uses: actions/checkout@v2

      # Setup do AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Ajuste para sua região

      # Login no Amazon ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 024848472141.dkr.ecr.us-east-2.amazonaws.com

      # Build da imagem Docker
      - name: Build the Docker image
        run: |
          docker build -t repository_name .

      # Tag da imagem com o SHA do commit
      - name: Tag the Docker image
        run: |
          docker tag repository_name:024848472141.dkr.ecr.us-east-2.amazonaws.com/helloaws:latest

      # Push da imagem para o ECR
      - name: Push Docker image to Amazon ECR
        run: |
          docker push 024848472141.dkr.ecr.us-east-2.amazonaws.com/repository_name:latest
